schema_version: 1

context:
  version: "0.14.0"

package:
  name: redisvl
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/r/redisvl/redisvl-${{ version }}.tar.gz
  sha256: 7a84c46858dbc86943e64ffe8590013684d03d79b72a634d10c02ce5d1c02335

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - rvl = redisvl.cli.runner:main

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - numpy >=1.26.0,<3
    - pyyaml >=5.4,<7.0
    - redis-py >=5.0,<7.2
    - pydantic >=2,<3
    - tenacity >=8.2.2
    - ml_dtypes >=0.4.0,<1.0.0
    - python-ulid >=3.0.0
    - jsonpath-ng >=1.5.0

tests:
  - python:
      imports:
        - redisvl
        - redisvl.index
        - redisvl.query
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - 3.*
  - script:
      - rvl --help
    requirements:
      run:
        - python ${{ python_min }}.*

about:
  summary: Python client library and CLI for using Redis as a vector database
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/redis/redis-vl-python
  documentation: https://docs.redisvl.com

extra:
  recipe-maintainers:
    - beenje
